// Find TODO statements and complete them to build the interactive airline route map.

// TODO: add your uniqname to the HTML (use id #uniqname) file so that your work can be identified 
document.getElementById("uniqname").textContent = "alogaili";
// TODO: import data using d3.csv()
const dataFile = await d3.csv("data/routes.csv");

const colornone = "#ccc";

// define colors for airlines, you can expand this as needed, WN is Southwest, B6 is JetBlue
const airlineColor = { WN: "orange", B6: "steelblue" };
const airlineName = { WN: "Southwest Airlines", B6: "JetBlue" };

// create options from selector that allows us to view all airlines or filter by a specific airline
const airlines = ["all", ...new Set(dataFile.map(d => d.Airline))];

// build selector from data
const select = d3.select("body")
    .insert("select", "#chart")
    .on("change", function () { draw(this.value); });

select.selectAll("option")
    .data(airlines)
    .join("option")
    .attr("value", d => d)
    .text(// TODO: build options from selector that allows us to view all airlines or filter by a specific airline);
        d => d === "all" ? "All Airlines" : (airlineName[d] || d));
// helper function to build outgoing links for each leaf node
function bilink(root) {
    // create a map of leaf nodes for quick lookup, using the unique ID generated by the id() function
    const map = new Map(root.leaves().map(d => [id(d), d]));

    // for each leaf node, build an outgoing array of [source, target, airline] tuples
    for (const d of root.leaves()) {
        d.outgoing = d.data.destinations
            .map(({ target, airline, targetRegion }) => [d, map.get(`root/${targetRegion}/${target}`), airline])
            .filter(([, target]) => target !== undefined);
    }

    return root;
}

// helper function to generate a unique ID for each node based on its position in the hierarchy
function id(node) {
    return `${node.parent ? id(node.parent) + "/" : ""}${node.data.name}`;
}

//rebuild hierarchy data and redraw chart on selection change
function draw(airlineFilter) {

    // filter data based on selection, if "all" is selected, use the entire dataset
    const filtered = airlineFilter === "all"
        ? dataFile
        : dataFile.filter(d => d.Airline === airlineFilter);

    // group data by source region and then by source airport
    const grouped = d3.group(filtered, d => d["Source region"], d => d["Source airport"]);

    // transform grouped data into a hierarchy format suitable for the chart
    const hierarchyData = {
        name: "root",
        children: Array.from(grouped, ([region, airports]) => ({
            name: region,
            children: Array.from(airports, ([airport, routes]) => ({
                name: airport,
                destinations: routes.map(r => ({ target: r["Destination airport"], airline: r.Airline, targetRegion: r["Destination region"] }))
            }))
        }))
    };

    document.getElementById("chart").innerHTML = "";
    document.getElementById("chart").appendChild(createChart(hierarchyData));
}

draw("all"); // initial draw


// TODO: integrate code from Observable notebook https://observablehq.com/@d3/hierarchical-edge-bundling 
// TODO: edit the tooltip to show the airport code, the region, and the number of outgoing and incoming routes for that airport
// TODO: edit link to show different colors for different airlines, you can use the airlineColor object defined above for reference
// TODO: edit overed and outed functions to highlight connected links and nodes on hover
function createChart(data) {
 
    const width = 954;
    const radius = width / 2;
 
    // build the radial cluster tree layout
    const tree = d3.cluster()
        .size([2 * Math.PI, radius - 100]);
 
    // build hierarchy, sort, run bilink to attach outgoing arrays, then apply layout
    const root = tree(bilink(d3.hierarchy(data)
        .sort((a, b) => d3.ascending(a.height, b.height) || d3.ascending(a.data.name, b.data.name))));
 
    // create the SVG container
    const svg = d3.create("svg")
        .attr("width", width)
        .attr("height", width)
        .attr("viewBox", [-width / 2, -width / 2, width, width])
        .attr("style", "max-width: 100%; height: auto; font: 10px sans-serif;");
 
    // radial line generator using bundle curve for edge bundling effect
    const line = d3.lineRadial()
        .curve(d3.curveBundle.beta(0.85))
        .radius(d => d.y)
        .angle(d => d.x);
 
    // draw all route links
    // TODO: edit link to show different colors for different airlines
    const link = svg.append("g")
        .attr("fill", "none")
        .attr("stroke-opacity", 0.6)
        .selectAll("path")
        .data(root.leaves().flatMap(leaf => leaf.outgoing))
        .join("path")
        .style("mix-blend-mode", "multiply")
        .attr("stroke", ([source, , airline]) => airlineColor[airline] || colornone)
        .attr("d", ([source, target]) => line(source.path(target)))
        .each(function([source, target]) {
            // store source/target references on the DOM element for use in hover
            this.source = source;
            this.target = target;
        });
 
    // draw airport label nodes around the circle
    const node = svg.append("g")
        .selectAll("g")
        .data(root.leaves())
        .join("g")
        .attr("transform", d => `rotate(${d.x * 180 / Math.PI - 90}) translate(${d.y},0)`)
        .append("text")
        .attr("dy", "0.31em")
        .attr("x", d => d.x < Math.PI ? 6 : -6)
        .attr("text-anchor", d => d.x < Math.PI ? "start" : "end")
        .attr("transform", d => d.x >= Math.PI ? "rotate(180)" : null)
        .text(d => d.data.name)
        .on("mouseover", overed)
        .on("mouseout", outed)
        // TODO: edit the tooltip to show the airport code, the region, and the number of outgoing and incoming routes
        .call(text => text.append("title")
            .text(d => {
                const airport = d.data.name;
                const region = d.parent ? d.parent.data.name : "";
                const outgoingCount = d.outgoing ? d.outgoing.length : 0;
                const incomingCount = root.leaves()
                    .filter(leaf => leaf.outgoing && leaf.outgoing.some(([, target]) => target === d))
                    .length;
                return `Airport: ${airport}\nRegion: ${region}\nOutgoing routes: ${outgoingCount}\nIncoming routes: ${incomingCount}`;
            })
        );
 
    // TODO: edit overed and outed functions to highlight connected links and nodes on hover
    function overed(event, d) {
        // bold the hovered label
        d3.select(this).attr("font-weight", "bold");
 
        // dim all links to start
        link.attr("stroke", colornone).attr("stroke-opacity", 0.1);
 
        // highlight outgoing links from this node in airline color
        if (d.outgoing) {
            d.outgoing.forEach(([source, target, airline]) => {
                link
                    .filter(function() { return this.source === source && this.target === target; })
                    .attr("stroke", airlineColor[airline] || colornone)
                    .attr("stroke-opacity", 1)
                    .raise();
            });
        }
 
        // highlight incoming links to this node in airline color
        root.leaves().forEach(leaf => {
            if (leaf.outgoing) {
                leaf.outgoing.forEach(([source, target, airline]) => {
                    if (target === d) {
                        link
                            .filter(function() { return this.source === source && this.target === target; })
                            .attr("stroke", airlineColor[airline] || colornone)
                            .attr("stroke-opacity", 1)
                            .raise();
                    }
                });
            }
        });
 
        // color connected text labels: outgoing targets red, incoming sources blue, others grey
        node
            .attr("fill", n => {
                if (n === d) return "black";
                if (d.outgoing && d.outgoing.some(([, target]) => target === n)) return "red";
                if (n.outgoing && n.outgoing.some(([, target]) => target === d)) return "steelblue";
                return "#ccc";
            })
            .attr("font-weight", n =>
                n === d ||
                (d.outgoing && d.outgoing.some(([, target]) => target === n)) ||
                (n.outgoing && n.outgoing.some(([, target]) => target === d))
                    ? "bold" : null
            );
    }
 
    function outed(event, d) {
        // restore all links to default airline color and opacity
        link
            .style("mix-blend-mode", "multiply")
            .attr("stroke", ([source, , airline]) => airlineColor[airline] || colornone)
            .attr("stroke-opacity", 0.6);
 
        // restore all node labels to default
        node
            .attr("fill", null)
            .attr("font-weight", null);
    }
 
    return svg.node();
}